[2023-03-10 09:33:06,245] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-03-10 09:33:06,249] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-02-06T00:00:00+00:00 [queued]>
[2023-03-10 09:33:06,250] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 09:33:06,250] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-10 09:33:06,250] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-10 09:33:06,263] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2023-02-06 00:00:00+00:00
[2023-03-10 09:33:06,269] {standard_task_runner.py:52} INFO - Started process 15918 to run task
[2023-03-10 09:33:06,277] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2023-02-06T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dado_climaticos.py', '--cfg-path', '/tmp/tmp0nchef62', '--error-file', '/tmp/tmpuiy7bpat']
[2023-03-10 09:33:06,278] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2023-03-10 09:33:06,326] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2023-02-06T00:00:00+00:00 [running]> on host gabriel-yuto
[2023-03-10 09:33:06,357] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 387, in render_template
    template = jinja_env.from_string(value)
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1092, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/home/gabriel/Documents/projetos/apache-airflow/alura-apache-airflow-orquestrando-primeiro-pipeline-dados/airflow-alura/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected end of template, expected ','.
[2023-03-10 09:33:06,369] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20230206T000000, start_date=20230310T123306, end_date=20230310T123306
[2023-03-10 09:33:06,382] {standard_task_runner.py:92} ERROR - Failed to execute job 20 for task cria_pasta (unexpected end of template, expected ','.; 15918)
[2023-03-10 09:33:06,417] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-10 09:33:06,451] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
